Repository theforeman/foreman-ansible-modules, pull requests merged in 2018-06, with the labels that each got.

#126 Print import errors
  module_utils/foreman_helper.py
  modules/foreman_compute_profile.py
  modules/foreman_compute_resource.py
  modules/foreman_domain.py
  modules/foreman_global_parameter.py
  modules/foreman_location.py
  modules/foreman_operating_system.py
  modules/foreman_organization.py
  modules/foreman_os_default_template.py
  modules/foreman_provisioning_template.py
  modules/foreman_ptable.py
  modules/foreman_realm.py
  modules/foreman_setting.py
  modules/foreman_setting_facts.py
  modules/katello_activation_key.py
  modules/katello_content_view.py
  modules/katello_content_view_publish.py
  modules/katello_content_view_version_promote.py
  modules/katello_lifecycle_environment.py
  modules/katello_manifest.py
  modules/katello_product.py
  modules/katello_repository.py
  modules/katello_repository_set.py
  modules/katello_sync.py
  modules/katello_sync_plan.py
  modules/katello_upload.py
Labels: ready to merge

#125 Add job templates module
  README.md
  module_utils/ansible_nailgun_cement.py
  modules/foreman_job_template.py
  test/test_crud.py
  test/test_playbooks/delete_file.erb
  test/test_playbooks/fixtures/job_template-1.yml
  test/test_playbooks/fixtures/job_template-11.yml
  test/test_playbooks/fixtures/job_template-13.yml
  test/test_playbooks/fixtures/job_template-15.yml
  test/test_playbooks/fixtures/job_template-17.yml
  test/test_playbooks/fixtures/job_template-3.yml
  test/test_playbooks/fixtures/job_template-5.yml
  test/test_playbooks/fixtures/job_template-7.yml
  test/test_playbooks/fixtures/job_template-9.yml
  test/test_playbooks/job_template.yml
  test/test_playbooks/tasks/job_template.yml
  test/test_playbooks/tasks/job_template_from_file.yml
Labels: enhancement, ready to merge

#134 add auto_attach param to katello_activation_key
  modules/katello_activation_key.py
  test/test_crud.py
  test/test_playbooks/activation_key.yml
  test/test_playbooks/fixtures/activation_key-1.yml
  test/test_playbooks/fixtures/activation_key-3.yml
  test/test_playbooks/fixtures/activation_key-5.yml
  test/test_playbooks/fixtures/activation_key-7.yml
  test/test_playbooks/tasks/activation_key.yml
Labels: enhancement, ready to merge

#136 fix typo in documentation
  modules/katello_content_view_publish.py
Labels: ready to merge

#131 Fix finding comment in template
  module_utils/foreman_helper.py
Labels: bug fix, needs reviewers
