Repository theforeman/foreman-ansible-modules, pull requests merged in 2018-09, with the labels that each got.

#173 update redhat_manifest distributor_version
  modules/redhat_manifest.py
Labels: needs reviewers

#175 Fix Job Template module
  module_utils/ansible_nailgun_cement.py
  modules/foreman_job_template.py
Labels: bug fix, needs reviewers

#133 Return the modified entity from setting module
  modules/foreman_setting.py
  test/test_playbooks/tasks/setting.yml
Labels: enhancement
