Repository theforeman/foreman-ansible-modules, pull requests merged in 2019-11, with the labels that each got.

#559 Foreman_subnet: add template_proxy option
  plugins/modules/foreman_subnet.py
Labels: needs tests, triaged, waiting on contributor

#553 Foreman_subnet: add IPAM choice None
  plugins/modules/foreman_subnet.py
Labels: needs tests, triaged, waiting on contributor

#557 update katello.json to 3.13
  tests/fixtures/apidoc/katello-3.11.json
  tests/fixtures/apidoc/katello-3.12.json
  tests/fixtures/apidoc/katello.json
Labels: triaged

#587 Record changed state on module
  plugins/module_utils/foreman_helper.py
  plugins/modules/foreman_architecture.py
  plugins/modules/foreman_auth_source_ldap.py
  plugins/modules/foreman_bookmark.py
  plugins/modules/foreman_compute_attribute.py
  plugins/modules/foreman_compute_profile.py
  plugins/modules/foreman_compute_resource.py
  plugins/modules/foreman_config_group.py
  plugins/modules/foreman_domain.py
  plugins/modules/foreman_environment.py
  plugins/modules/foreman_external_usergroup.py
  plugins/modules/foreman_global_parameter.py
  plugins/modules/foreman_host.py
  plugins/modules/foreman_host_power.py
  plugins/modules/foreman_hostgroup.py
  plugins/modules/foreman_installation_medium.py
  plugins/modules/foreman_job_template.py
  plugins/modules/foreman_location.py
  plugins/modules/foreman_operatingsystem.py
  plugins/modules/foreman_organization.py
  plugins/modules/foreman_os_default_template.py
  plugins/modules/foreman_provisioning_template.py
  plugins/modules/foreman_ptable.py
  plugins/modules/foreman_realm.py
  plugins/modules/foreman_role.py
  plugins/modules/foreman_search_facts.py
  plugins/modules/foreman_setting.py
  plugins/modules/foreman_snapshot.py
  plugins/modules/foreman_subnet.py
  plugins/modules/foreman_user.py
  plugins/modules/foreman_usergroup.py
  plugins/modules/katello_activation_key.py
  plugins/modules/katello_content_credential.py
  plugins/modules/katello_content_view.py
  plugins/modules/katello_content_view_filter.py
  plugins/modules/katello_content_view_version.py
  plugins/modules/katello_host_collection.py
  plugins/modules/katello_lifecycle_environment.py
  plugins/modules/katello_manifest.py
  plugins/modules/katello_product.py
  plugins/modules/katello_repository.py
  plugins/modules/katello_repository_set.py
  plugins/modules/katello_sync.py
  plugins/modules/katello_sync_plan.py
  plugins/modules/katello_upload.py
Labels: enhancement, refactor, triaged

#603 Fix recording subnet by ignoring proxy name
  tests/test_playbooks/vars/subnet.yml
  tests/vcr_python_wrapper.py
Labels: triaged

#552 Add netgroups option to auth_source_ldap
  docs/testing.md
  plugins/modules/foreman_auth_source_ldap.py
  tests/test_playbooks/auth_source_ldap.yml
  tests/test_playbooks/fixtures/auth_source_ldap-0.yml
  tests/test_playbooks/fixtures/auth_source_ldap-1.yml
  tests/test_playbooks/fixtures/auth_source_ldap-2.yml
  tests/test_playbooks/fixtures/auth_source_ldap-3.yml
  tests/test_playbooks/fixtures/auth_source_ldap-4.yml
  tests/test_playbooks/fixtures/auth_source_ldap-5.yml
  tests/test_playbooks/fixtures/auth_source_ldap-6.yml
  tests/test_playbooks/tasks/auth_source_ldap.yml
Labels: triaged

#621 Use list for extends_documentation_fragment
  Makefile
  plugins/modules/foreman_architecture.py
  plugins/modules/foreman_auth_source_ldap.py
  plugins/modules/foreman_bookmark.py
  plugins/modules/foreman_compute_attribute.py
  plugins/modules/foreman_compute_profile.py
  plugins/modules/foreman_compute_resource.py
  plugins/modules/foreman_config_group.py
  plugins/modules/foreman_domain.py
  plugins/modules/foreman_environment.py
  plugins/modules/foreman_external_usergroup.py
  plugins/modules/foreman_global_parameter.py
  plugins/modules/foreman_host.py
  plugins/modules/foreman_host_power.py
  plugins/modules/foreman_hostgroup.py
  plugins/modules/foreman_installation_medium.py
  plugins/modules/foreman_job_template.py
  plugins/modules/foreman_location.py
  plugins/modules/foreman_operatingsystem.py
  plugins/modules/foreman_organization.py
  plugins/modules/foreman_os_default_template.py
  plugins/modules/foreman_provisioning_template.py
  plugins/modules/foreman_ptable.py
  plugins/modules/foreman_realm.py
  plugins/modules/foreman_role.py
  plugins/modules/foreman_search_facts.py
  plugins/modules/foreman_setting.py
  plugins/modules/foreman_snapshot.py
  plugins/modules/foreman_subnet.py
  plugins/modules/foreman_user.py
  plugins/modules/foreman_usergroup.py
  plugins/modules/katello_activation_key.py
  plugins/modules/katello_content_credential.py
  plugins/modules/katello_content_view.py
  plugins/modules/katello_content_view_filter.py
  plugins/modules/katello_content_view_version.py
  plugins/modules/katello_host_collection.py
  plugins/modules/katello_lifecycle_environment.py
  plugins/modules/katello_manifest.py
  plugins/modules/katello_product.py
  plugins/modules/katello_repository.py
  plugins/modules/katello_repository_set.py
  plugins/modules/katello_sync.py
  plugins/modules/katello_sync_plan.py
  plugins/modules/katello_upload.py
Labels: needs reviewers
