Repository theforeman/foreman-ansible-modules, pull requests merged in 2019-06, with the labels that each got.

#302 Use 'vars_files' in test_playbooks.
  .gitignore
  Makefile
  README.md
  test/README.md
  test/test_playbooks/activation_key.yml
  test/test_playbooks/bookmark.yml
  test/test_playbooks/compute_profile.yml
  test/test_playbooks/compute_resource.yml
  test/test_playbooks/content_credential.yml
  test/test_playbooks/content_view.yml
  test/test_playbooks/content_view_filter.yml
  test/test_playbooks/content_view_version_promote.yml
  test/test_playbooks/domain.yml
  test/test_playbooks/environment.yml
  test/test_playbooks/fixtures/repository_set-0.yml
  test/test_playbooks/fixtures/repository_set-1.yml
  test/test_playbooks/fixtures/repository_set-2.yml
  test/test_playbooks/fixtures/repository_set-3.yml
  test/test_playbooks/fixtures/repository_set-4.yml
  test/test_playbooks/fixtures/repository_set-5.yml
  test/test_playbooks/global_parameter.yml
  test/test_playbooks/host.yml
  test/test_playbooks/host_collection.yml
  test/test_playbooks/installation_medium.yml
  test/test_playbooks/job_template.yml
  test/test_playbooks/katello_manifest.yml
  test/test_playbooks/lifecycle_environment.yml
  test/test_playbooks/location.yml
  test/test_playbooks/operating_system.yml
  test/test_playbooks/organization.yml
  test/test_playbooks/os_default_template.yml
  test/test_playbooks/power_host.yml
  test/test_playbooks/product.yml
  test/test_playbooks/provisioning_template.yml
  test/test_playbooks/ptable.yml
  test/test_playbooks/realm.yml
  test/test_playbooks/redhat_manifest.yml
  test/test_playbooks/repository.yml
  test/test_playbooks/repository_set.yml
  test/test_playbooks/repository_sync.yml
  test/test_playbooks/role.yml
  test/test_playbooks/search_facts.yml
  test/test_playbooks/setting.yml
  test/test_playbooks/subnet.yml
  test/test_playbooks/sync_plan.yml
  test/test_playbooks/upload.yml
  test/test_playbooks/vars/compute_profile.yml
  test/test_playbooks/vars/domain.yml
  test/test_playbooks/vars/server.yml.example
  test/test_playbooks/vars/subnet.yml
Labels: refactor

#286 Add module for LDAP authentication source
  plugins/modules/foreman_auth_source_ldap.py
  test/test_crud.py
  test/test_playbooks/auth_source_ldap.yml
  test/test_playbooks/fixtures/auth_source_ldap-0.yml
  test/test_playbooks/fixtures/auth_source_ldap-1.yml
  test/test_playbooks/fixtures/auth_source_ldap-2.yml
  test/test_playbooks/fixtures/auth_source_ldap-3.yml
  test/test_playbooks/fixtures/auth_source_ldap-4.yml
  test/test_playbooks/tasks/auth_source_ldap.yml
Labels: enhancement

#301 Modify vcr_python_wrapper for host test
  test/test_playbooks/tasks/host.yml
  test/test_playbooks/vars/server.yml.example
  test/vcr_python_wrapper.py
Labels: ready to merge
