Repository theforeman/foreman-ansible-modules, pull requests merged in 2019-08, with the labels that each got.

#376 Entity spec
  plugins/__init__.py
  plugins/module_utils/foreman_helper.py
  plugins/modules/foreman_architecture.py
  plugins/modules/foreman_domain.py
  tests/test_entity_spec_helper.py
Labels: refactor

#388 Rename foreman_operatingsystem
  plugins/modules/foreman_operatingsystem.py
  tests/fixtures/apidoc/operatingsystem.json
  tests/test_crud.py
  tests/test_playbooks/fixtures/operatingsystem-0.yml
  tests/test_playbooks/fixtures/operatingsystem-1.yml
  tests/test_playbooks/fixtures/operatingsystem-10.yml
  tests/test_playbooks/fixtures/operatingsystem-2.yml
  tests/test_playbooks/fixtures/operatingsystem-3.yml
  tests/test_playbooks/fixtures/operatingsystem-4.yml
  tests/test_playbooks/fixtures/operatingsystem-5.yml
  tests/test_playbooks/fixtures/operatingsystem-6.yml
  tests/test_playbooks/fixtures/operatingsystem-7.yml
  tests/test_playbooks/fixtures/operatingsystem-8.yml
  tests/test_playbooks/fixtures/operatingsystem-9.yml
  tests/test_playbooks/operating_system.yml
  tests/test_playbooks/operatingsystem.yml
  tests/test_playbooks/tasks/operating_system.yml
  tests/test_playbooks/tasks/operatingsystem.yml
Labels: question

#390 Port katello_sync_plan to foreman_helper
  plugins/module_utils/foreman_helper.py
  plugins/modules/katello_sync_plan.py
  tests/test_playbooks/fixtures/sync_plan-0.yml
  tests/test_playbooks/fixtures/sync_plan-1.yml
  tests/test_playbooks/fixtures/sync_plan-2.yml
  tests/test_playbooks/fixtures/sync_plan-3.yml
  tests/test_playbooks/fixtures/sync_plan-4.yml
  tests/test_playbooks/fixtures/sync_plan-5.yml
  tests/test_playbooks/fixtures/sync_plan-6.yml
  tests/test_playbooks/sync_plan.yml
  tests/test_playbooks/tasks/sync_plan.yml
Labels: refactor

#393 Refactor activation key
  plugins/module_utils/foreman_helper.py
  plugins/modules/katello_activation_key.py
  tests/fixtures/apidoc/katello-3.11.json
  tests/fixtures/apidoc/katello-3.12.json
  tests/fixtures/apidoc/katello.json
  tests/test_playbooks/activation_key.yml
  tests/test_playbooks/fixtures/activation_key-0.yml
  tests/test_playbooks/fixtures/activation_key-1.yml
  tests/test_playbooks/fixtures/activation_key-10.yml
  tests/test_playbooks/fixtures/activation_key-2.yml
  tests/test_playbooks/fixtures/activation_key-3.yml
  tests/test_playbooks/fixtures/activation_key-4.yml
  tests/test_playbooks/fixtures/activation_key-5.yml
  tests/test_playbooks/fixtures/activation_key-6.yml
  tests/test_playbooks/fixtures/activation_key-7.yml
  tests/test_playbooks/fixtures/activation_key-8.yml
  tests/test_playbooks/fixtures/activation_key-9.yml
  tests/test_playbooks/tasks/activation_key.yml
  tests/test_playbooks/tasks/activation_key_minimal.yml
Labels: refactor

#380 Modify foreman_compute_resource module for apypie
  plugins/modules/foreman_compute_resource.py
  tests/test_playbooks/compute_resource.yml
  tests/test_playbooks/fixtures/compute_resource-0.yml
  tests/test_playbooks/fixtures/compute_resource-1.yml
  tests/test_playbooks/fixtures/compute_resource-2.yml
  tests/test_playbooks/fixtures/compute_resource-3.yml
  tests/test_playbooks/fixtures/compute_resource-4.yml
  tests/test_playbooks/fixtures/compute_resource-5.yml
  tests/test_playbooks/fixtures/compute_resource-6.yml
  tests/test_playbooks/fixtures/compute_resource-7.yml
  tests/test_playbooks/fixtures/compute_resource-8.yml
  tests/test_playbooks/fixtures/compute_resource-9.yml
Labels: ready to merge, refactor

#403 migrate katello_upload to apypie
  Makefile
  plugins/module_utils/foreman_helper.py
  plugins/modules/katello_manifest.py
  plugins/modules/katello_upload.py
  tests/test_playbooks/fixtures/upload-0.yml
  tests/test_playbooks/fixtures/upload-1.yml
  tests/test_playbooks/fixtures/upload-2.yml
  tests/test_playbooks/fixtures/upload-3.yml
  tests/test_playbooks/upload.yml
  tests/vcr_python_wrapper.py
Labels: refactor

#446 Add a filter to produce candle_pin labels
  ansible.cfg
  plugins/filter/foreman.py
  tests/fixtures/apidoc/filters.json
  tests/test_crud.py
  tests/test_playbooks/filters.yml
Labels: enhancement

#448 Add alias to vm_attrs
  plugins/modules/foreman_compute_attribute.py
  plugins/modules/foreman_compute_profile.py
Labels: enhancement
