Repository theforeman/foreman-ansible-modules, pull requests merged in 2019-12, with the labels that each got.

#617 add a release workflow to publish to galaxy
  .github/workflows/release.yml
Labels: triaged

#643 Remove asynchronous feature
  README.md
  plugins/module_utils/foreman_helper.py
  plugins/modules/katello_content_view_version.py
  plugins/modules/katello_sync.py
  tests/test_playbooks/fixtures/katello_sync-1.yml
  tests/test_playbooks/fixtures/katello_sync-2.yml
  tests/test_playbooks/fixtures/katello_sync-3.yml
  tests/test_playbooks/katello_sync.yml
  tests/test_playbooks/tasks/content_view_version.yml
  tests/test_playbooks/tasks/katello_sync.yml
Labels: enhancement, ready to merge, triaged

#588 Add Scc_account module
  plugins/module_utils/foreman_helper.py
  plugins/modules/foreman_scc_account.py
  plugins/modules/katello_manifest.py
  tests/conftest.py
  tests/fixtures/apidoc/scc_account.json
  tests/test_playbooks/fixtures/scc_account-0.yml
  tests/test_playbooks/fixtures/scc_account-1.yml
  tests/test_playbooks/fixtures/scc_account-2.yml
  tests/test_playbooks/fixtures/scc_account-3.yml
  tests/test_playbooks/fixtures/scc_account-4.yml
  tests/test_playbooks/fixtures/scc_account-5.yml
  tests/test_playbooks/fixtures/scc_account-6.yml
  tests/test_playbooks/fixtures/scc_account-7.yml
  tests/test_playbooks/fixtures/scc_account-8.yml
  tests/test_playbooks/scc_account.yml
  tests/test_playbooks/tasks/scc_account.yml
Labels: triaged

#660 update apidoc for katello 3.14
  plugins/modules/katello_upload.py
  tests/fixtures/apidoc/katello.json
  tests/test_playbooks/fixtures/activation_key-0.yml
  tests/test_playbooks/fixtures/activation_key-1.yml
  tests/test_playbooks/fixtures/activation_key-10.yml
  tests/test_playbooks/fixtures/activation_key-11.yml
  tests/test_playbooks/fixtures/activation_key-12.yml
  tests/test_playbooks/fixtures/activation_key-13.yml
  tests/test_playbooks/fixtures/activation_key-14.yml
  tests/test_playbooks/fixtures/activation_key-15.yml
  tests/test_playbooks/fixtures/activation_key-16.yml
  tests/test_playbooks/fixtures/activation_key-17.yml
  tests/test_playbooks/fixtures/activation_key-18.yml
  tests/test_playbooks/fixtures/activation_key-19.yml
  tests/test_playbooks/fixtures/activation_key-2.yml
  tests/test_playbooks/fixtures/activation_key-20.yml
  tests/test_playbooks/fixtures/activation_key-21.yml
  tests/test_playbooks/fixtures/activation_key-22.yml
  tests/test_playbooks/fixtures/activation_key-23.yml
  tests/test_playbooks/fixtures/activation_key-24.yml
  tests/test_playbooks/fixtures/activation_key-25.yml
  tests/test_playbooks/fixtures/activation_key-26.yml
  tests/test_playbooks/fixtures/activation_key-27.yml
  tests/test_playbooks/fixtures/activation_key-28.yml
  tests/test_playbooks/fixtures/activation_key-29.yml
  tests/test_playbooks/fixtures/activation_key-3.yml
  tests/test_playbooks/fixtures/activation_key-30.yml
  tests/test_playbooks/fixtures/activation_key-31.yml
  tests/test_playbooks/fixtures/activation_key-32.yml
  tests/test_playbooks/fixtures/activation_key-4.yml
  tests/test_playbooks/fixtures/activation_key-5.yml
  tests/test_playbooks/fixtures/activation_key-6.yml
  tests/test_playbooks/fixtures/activation_key-7.yml
  tests/test_playbooks/fixtures/activation_key-8.yml
  tests/test_playbooks/fixtures/activation_key-9.yml
  tests/test_playbooks/fixtures/upload-0.yml
  tests/test_playbooks/fixtures/upload-1.yml
  tests/test_playbooks/fixtures/upload-2.yml
  tests/test_playbooks/fixtures/upload-3.yml
  tests/test_playbooks/fixtures/upload-4.yml
  tests/test_playbooks/fixtures/upload-5.yml
Labels: WIP, waiting on another PR

#663 require the mail parameter for creating a new user
  plugins/modules/foreman_user.py
Labels: bug, triaged

#609 Fix some random unicode problems
  plugins/module_utils/foreman_helper.py
  plugins/modules/katello_content_view_filter.py
  plugins/modules/katello_upload.py
  plugins/modules/redhat_manifest.py
  tests/test_entity_spec_helper.py
  tests/test_playbooks/architecture.yml
  tests/test_playbooks/fixtures/architecture-0.yml
  tests/test_playbooks/fixtures/architecture-1.yml
  tests/test_playbooks/fixtures/architecture-10.yml
  tests/test_playbooks/fixtures/architecture-11.yml
  tests/test_playbooks/fixtures/architecture-2.yml
  tests/test_playbooks/fixtures/architecture-3.yml
  tests/test_playbooks/fixtures/architecture-4.yml
  tests/test_playbooks/fixtures/architecture-5.yml
  tests/test_playbooks/fixtures/architecture-6.yml
  tests/test_playbooks/fixtures/architecture-7.yml
  tests/test_playbooks/fixtures/architecture-8.yml
  tests/test_playbooks/fixtures/architecture-9.yml
  tests/test_playbooks/tasks/architecture.yml
Labels: triaged
