Repository theforeman/foreman-ansible-modules, pull requests merged in 2019-03, with the labels that each got.

#247 Use consistent parameters in subnet module documentation
  modules/foreman_subnet.py
Labels: bug fix, ready to merge

#248 Remove local entities
  module_utils/ansible_nailgun_cement.py
Labels: needs reviewers, refactor

#258 Repair activation_key test
  Makefile
  modules/katello_activation_key.py
  test/test_crud.py
  test/test_playbooks/activation_key.yml
  test/test_playbooks/fixtures/activation_key-0.yml
  test/test_playbooks/fixtures/activation_key-1.yml
  test/test_playbooks/fixtures/activation_key-2.yml
  test/test_playbooks/fixtures/activation_key-3.yml
  test/test_playbooks/fixtures/activation_key-4.yml
  test/test_playbooks/fixtures/activation_key-5.yml
  test/test_playbooks/fixtures/activation_key-6.yml
  test/test_playbooks/fixtures/activation_key-7.yml
  test/test_playbooks/fixtures/activation_key-8.yml
  test/test_playbooks/fixtures/activation_key-9.yml
  test/test_playbooks/tasks/activation_key.yml
Labels: bug fix, needs reviewers, refactor
