Repository theforeman/foreman-ansible-modules, pull requests merged in 2019-10, with the labels that each got.

#533 document that mazer is for 2.8 and ansible-galaxy is for 2.9+
  README.md
Labels: enhancement

#527 Add filters support for roles.
  plugins/modules/foreman_role.py
  tests/test_playbooks/fixtures/role-0.yml
  tests/test_playbooks/fixtures/role-1.yml
  tests/test_playbooks/fixtures/role-2.yml
  tests/test_playbooks/fixtures/role-3.yml
  tests/test_playbooks/fixtures/role-4.yml
  tests/test_playbooks/fixtures/role-5.yml
  tests/test_playbooks/fixtures/role-6.yml
  tests/test_playbooks/role.yml
  tests/test_playbooks/tasks/role.yml
Labels: enhancement, waiting on contributor

#516 Add foreman_usergroup module
  plugins/modules/foreman_usergroup.py
  tests/conftest.py
  tests/fixtures/apidoc/usergroup.json
  tests/sanity/ignore-2.10.txt
  tests/test_playbooks/fixtures/usergroup-0.yml
  tests/test_playbooks/fixtures/usergroup-1.yml
  tests/test_playbooks/fixtures/usergroup-10.yml
  tests/test_playbooks/fixtures/usergroup-11.yml
  tests/test_playbooks/fixtures/usergroup-12.yml
  tests/test_playbooks/fixtures/usergroup-2.yml
  tests/test_playbooks/fixtures/usergroup-3.yml
  tests/test_playbooks/fixtures/usergroup-4.yml
  tests/test_playbooks/fixtures/usergroup-5.yml
  tests/test_playbooks/fixtures/usergroup-6.yml
  tests/test_playbooks/fixtures/usergroup-7.yml
  tests/test_playbooks/fixtures/usergroup-8.yml
  tests/test_playbooks/fixtures/usergroup-9.yml
  tests/test_playbooks/tasks/usergroup.yml
  tests/test_playbooks/usergroup.yml
  tests/test_playbooks/vars/usergroup.yml
Labels: enhancement

#529 add subs to activation key by pool_id
  plugins/module_utils/foreman_helper.py
  plugins/modules/katello_activation_key.py
Labels: bug fix

#544 add basic tests for diff
  tests/test_playbooks/host_collection.yml
  tests/test_playbooks/organization.yml
  tests/test_playbooks/tasks/_assert_diff.yml
  tests/test_playbooks/tasks/host_collection.yml
  tests/test_playbooks/tasks/organization.yml
Labels: enhancement

#547 handle Katello-style errors in fail_from_exception
  plugins/module_utils/foreman_helper.py
Labels: bug fix

#545 store "before" state in ensure entity, not in find
  plugins/module_utils/foreman_helper.py
Labels: enhancement
