Repository theforeman/foreman-ansible-modules, pull requests merged in 2019-07, with the labels that each got.

#307 Add foreman compute_attribute module
  README.md
  plugins/modules/foreman_compute_attribute.py
  test/test_crud.py
  test/test_playbooks/compute_attribute.yml
  test/test_playbooks/fixtures/compute_attribute-0.yml
  test/test_playbooks/fixtures/compute_attribute-1.yml
  test/test_playbooks/fixtures/compute_attribute-2.yml
  test/test_playbooks/fixtures/compute_attribute-3.yml
  test/test_playbooks/tasks/compute_attribute.yml
  test/test_playbooks/tasks/compute_resource.yml
  test/test_playbooks/vars/compute_profile.yml
Labels: enhancement

#311 Add Hostgroup Module
  README.md
  plugins/modules/foreman_hostgroup.py
  test/test_crud.py
  test/test_playbooks/fixtures/hostgroup-0.yml
  test/test_playbooks/fixtures/hostgroup-1.yml
  test/test_playbooks/fixtures/hostgroup-2.yml
  test/test_playbooks/fixtures/hostgroup-3.yml
  test/test_playbooks/fixtures/hostgroup-4.yml
  test/test_playbooks/fixtures/hostgroup-5.yml
  test/test_playbooks/hostgroup.yml
  test/test_playbooks/tasks/hostgroup.yml
Labels: enhancement, waiting on contributor

#304 Thin query on absent
  plugins/module_utils/foreman_helper.py
  plugins/modules/foreman_auth_source_ldap.py
  plugins/modules/foreman_bookmark.py
  plugins/modules/foreman_domain.py
  plugins/modules/foreman_environment.py
  plugins/modules/foreman_hostgroup.py
  plugins/modules/foreman_organization.py
  plugins/modules/foreman_role.py
  plugins/modules/foreman_search_facts.py
  plugins/modules/foreman_user.py
  plugins/modules/katello_content_credential.py
  plugins/modules/katello_host_collection.py
  test/test_playbooks/fixtures/bookmark-0.yml
  test/test_playbooks/fixtures/bookmark-1.yml
  test/test_playbooks/fixtures/bookmark-2.yml
  test/test_playbooks/fixtures/bookmark-3.yml
  test/test_playbooks/fixtures/bookmark-4.yml
  test/test_playbooks/fixtures/bookmark-5.yml
  test/test_playbooks/fixtures/bookmark-6.yml
  test/test_playbooks/fixtures/content_credential-0.yml
  test/test_playbooks/fixtures/content_credential-1.yml
  test/test_playbooks/fixtures/content_credential-2.yml
  test/test_playbooks/fixtures/content_credential-3.yml
  test/test_playbooks/fixtures/content_credential-4.yml
  test/test_playbooks/fixtures/content_credential-5.yml
  test/test_playbooks/fixtures/content_credential-6.yml
  test/test_playbooks/fixtures/content_credential-7.yml
  test/test_playbooks/fixtures/domain-0.yml
  test/test_playbooks/fixtures/domain-1.yml
  test/test_playbooks/fixtures/domain-2.yml
  test/test_playbooks/fixtures/domain-3.yml
  test/test_playbooks/fixtures/domain-4.yml
  test/test_playbooks/fixtures/environment-0.yml
  test/test_playbooks/fixtures/environment-1.yml
  test/test_playbooks/fixtures/environment-2.yml
  test/test_playbooks/fixtures/environment-3.yml
  test/test_playbooks/fixtures/environment-4.yml
  test/test_playbooks/fixtures/environment-5.yml
  test/test_playbooks/fixtures/host_collection-0.yml
  test/test_playbooks/fixtures/host_collection-1.yml
  test/test_playbooks/fixtures/host_collection-2.yml
  test/test_playbooks/fixtures/host_collection-3.yml
  test/test_playbooks/fixtures/organization-0.yml
  test/test_playbooks/fixtures/organization-1.yml
  test/test_playbooks/fixtures/organization-2.yml
  test/test_playbooks/fixtures/organization-3.yml
  test/test_playbooks/fixtures/role-0.yml
  test/test_playbooks/fixtures/role-1.yml
  test/test_playbooks/fixtures/role-2.yml
  test/test_playbooks/fixtures/role-3.yml
  test/test_playbooks/fixtures/role-4.yml
Labels: enhancement, waiting on contributor

#230 move common documentation to a fragment
  README.md
  ansible.cfg
  plugins/doc_fragments/foreman.py
  plugins/modules/foreman_auth_source_ldap.py
  plugins/modules/foreman_bookmark.py
  plugins/modules/foreman_compute_attribute.py
  plugins/modules/foreman_compute_profile.py
  plugins/modules/foreman_compute_resource.py
  plugins/modules/foreman_domain.py
  plugins/modules/foreman_environment.py
  plugins/modules/foreman_global_parameter.py
  plugins/modules/foreman_host.py
  plugins/modules/foreman_host_power.py
  plugins/modules/foreman_hostgroup.py
  plugins/modules/foreman_installation_medium.py
  plugins/modules/foreman_job_template.py
  plugins/modules/foreman_location.py
  plugins/modules/foreman_operating_system.py
  plugins/modules/foreman_organization.py
  plugins/modules/foreman_os_default_template.py
  plugins/modules/foreman_provisioning_template.py
  plugins/modules/foreman_ptable.py
  plugins/modules/foreman_realm.py
  plugins/modules/foreman_role.py
  plugins/modules/foreman_search_facts.py
  plugins/modules/foreman_setting.py
  plugins/modules/foreman_setting_facts.py
  plugins/modules/foreman_subnet.py
  plugins/modules/foreman_user.py
  plugins/modules/katello_activation_key.py
  plugins/modules/katello_content_credential.py
  plugins/modules/katello_content_view.py
  plugins/modules/katello_content_view_filter.py
  plugins/modules/katello_content_view_publish.py
  plugins/modules/katello_content_view_version.py
  plugins/modules/katello_content_view_version_promote.py
  plugins/modules/katello_lifecycle_environment.py
  plugins/modules/katello_manifest.py
  plugins/modules/katello_product.py
  plugins/modules/katello_repository.py
  plugins/modules/katello_repository_set.py
  plugins/modules/katello_sync.py
  plugins/modules/katello_sync_plan.py
  plugins/modules/katello_upload.py
  plugins/modules/redhat_manifest.py
  test/extras/sanity.yml
Labels: refactor

#332 Refactor find methods
  Makefile
  plugins/module_utils/foreman_helper.py
  plugins/modules/foreman_architecture.py
  plugins/modules/foreman_auth_source_ldap.py
  plugins/modules/foreman_domain.py
  plugins/modules/foreman_environment.py
  plugins/modules/foreman_location.py
  plugins/modules/foreman_role.py
  plugins/modules/foreman_user.py
Labels: refactor

#327 Port installation_medium to apypie
  plugins/modules/foreman_installation_medium.py
  tests/test_playbooks/fixtures/installation_medium-0.yml
  tests/test_playbooks/fixtures/installation_medium-1.yml
  tests/test_playbooks/fixtures/installation_medium-2.yml
  tests/test_playbooks/fixtures/installation_medium-3.yml
  tests/test_playbooks/fixtures/installation_medium-4.yml
  tests/test_playbooks/fixtures/installation_medium-5.yml
  tests/test_playbooks/fixtures/installation_medium-6.yml
  tests/test_playbooks/fixtures/installation_medium-7.yml
  tests/test_playbooks/fixtures/installation_medium-8.yml
  tests/test_playbooks/fixtures/installation_medium-9.yml
Labels: refactor

#337 Refactor ensure resource
  plugins/module_utils/foreman_helper.py
  plugins/modules/foreman_architecture.py
  plugins/modules/foreman_auth_source_ldap.py
  plugins/modules/foreman_bookmark.py
  plugins/modules/foreman_compute_attribute.py
  plugins/modules/foreman_domain.py
  plugins/modules/foreman_environment.py
  plugins/modules/foreman_hostgroup.py
  plugins/modules/foreman_location.py
  plugins/modules/foreman_organization.py
  plugins/modules/foreman_role.py
  plugins/modules/foreman_user.py
  plugins/modules/katello_content_credential.py
  plugins/modules/katello_host_collection.py
  tests/test_playbooks/fixtures/architecture-0.yml
  tests/test_playbooks/fixtures/architecture-1.yml
  tests/test_playbooks/fixtures/architecture-2.yml
  tests/test_playbooks/fixtures/architecture-3.yml
  tests/test_playbooks/fixtures/architecture-4.yml
  tests/test_playbooks/fixtures/architecture-5.yml
Labels: refactor

#364 Port foreman_provisioning_template to apypie
  plugins/modules/foreman_provisioning_template.py
  plugins/modules/foreman_ptable.py
  tests/test_playbooks/fixtures/provisioning_template-0.yml
  tests/test_playbooks/fixtures/provisioning_template-1.yml
  tests/test_playbooks/fixtures/provisioning_template-10.yml
  tests/test_playbooks/fixtures/provisioning_template-11.yml
  tests/test_playbooks/fixtures/provisioning_template-12.yml
  tests/test_playbooks/fixtures/provisioning_template-13.yml
  tests/test_playbooks/fixtures/provisioning_template-14.yml
  tests/test_playbooks/fixtures/provisioning_template-2.yml
  tests/test_playbooks/fixtures/provisioning_template-3.yml
  tests/test_playbooks/fixtures/provisioning_template-4.yml
  tests/test_playbooks/fixtures/provisioning_template-5.yml
  tests/test_playbooks/fixtures/provisioning_template-6.yml
  tests/test_playbooks/fixtures/provisioning_template-7.yml
  tests/test_playbooks/fixtures/provisioning_template-8.yml
  tests/test_playbooks/fixtures/provisioning_template-9.yml
Labels: ready to merge, refactor

#306 Add Foreman Snapshot Module
  README.md
  plugins/module_utils/foreman_helper.py
  plugins/modules/foreman_snapshot.py
  tests/fixtures/apidoc/snapshot.json
  tests/test_crud.py
  tests/test_playbooks/fixtures/snapshot-0.yml
  tests/test_playbooks/fixtures/snapshot-1.yml
  tests/test_playbooks/fixtures/snapshot-2.yml
  tests/test_playbooks/fixtures/snapshot-3.yml
  tests/test_playbooks/fixtures/snapshot-4.yml
  tests/test_playbooks/fixtures/snapshot-5.yml
  tests/test_playbooks/fixtures/snapshot-6.yml
  tests/test_playbooks/snapshot.yml
  tests/test_playbooks/tasks/snapshot.yml
  tests/test_playbooks/vars/server.yml.example
  tests/vcr_python_wrapper.py
Labels: enhancement
