Repository theforeman/foreman-ansible-modules, pull requests merged in 2020-09, with the labels that each got.

#938 image module: fix quoting for search values
  plugins/modules/image.py
  tests/test_playbooks/fixtures/image-0.yml
  tests/test_playbooks/fixtures/image-1.yml
  tests/test_playbooks/fixtures/image-2.yml
  tests/test_playbooks/fixtures/image-3.yml
  tests/test_playbooks/fixtures/image-4.yml
  tests/test_playbooks/fixtures/image-5.yml
  tests/test_playbooks/fixtures/image-6.yml
  tests/test_playbooks/fixtures/image-7.yml
  tests/test_playbooks/image.yml
Labels: bug, triaged

#934 possibility to pass flags to test_ and record_ makefile entries
  Makefile
Labels: triaged

#939 added option "caching_enabled" to vmware
  changelogs/fragments/939-compute_resource-added_caching_enabled.yaml
  plugins/modules/compute_resource.py
Labels: enhancement, triaged, waiting on contributor

#936 update the list of supported repository params
  changelogs/fragments/935-repository-params.yaml
  plugins/modules/repository.py
Labels: needs reviewers, triaged

#931 Include blank parent groups
  changelogs/fragments/919-include-empty-parent-groups.yml
  plugins/inventory/foreman.py
  tests/test_playbooks/inventory_plugin.yml
Labels: bug, needs tests, triaged, waiting on contributor
