Repository theforeman/foreman-ansible-modules, pull requests merged in 2020-01, with the labels that each got.

#667 k_repository_set: only accept releasever and basearch for repositories
  plugins/modules/katello_repository_set.py
Labels: enhancement, triaged

#674 SSL certs
  plugins/modules/katello_product.py
  plugins/modules/katello_repository.py
  tests/test_playbooks/fixtures/product-0.yml
  tests/test_playbooks/fixtures/product-1.yml
  tests/test_playbooks/fixtures/product-10.yml
  tests/test_playbooks/fixtures/product-11.yml
  tests/test_playbooks/fixtures/product-12.yml
  tests/test_playbooks/fixtures/product-2.yml
  tests/test_playbooks/fixtures/product-3.yml
  tests/test_playbooks/fixtures/product-4.yml
  tests/test_playbooks/fixtures/product-5.yml
  tests/test_playbooks/fixtures/product-6.yml
  tests/test_playbooks/fixtures/product-7.yml
  tests/test_playbooks/fixtures/product-8.yml
  tests/test_playbooks/fixtures/product-9.yml
  tests/test_playbooks/fixtures/repository-0.yml
  tests/test_playbooks/fixtures/repository-1.yml
  tests/test_playbooks/fixtures/repository-10.yml
  tests/test_playbooks/fixtures/repository-11.yml
  tests/test_playbooks/fixtures/repository-12.yml
  tests/test_playbooks/fixtures/repository-13.yml
  tests/test_playbooks/fixtures/repository-14.yml
  tests/test_playbooks/fixtures/repository-15.yml
  tests/test_playbooks/fixtures/repository-16.yml
  tests/test_playbooks/fixtures/repository-17.yml
  tests/test_playbooks/fixtures/repository-18.yml
  tests/test_playbooks/fixtures/repository-19.yml
  tests/test_playbooks/fixtures/repository-2.yml
  tests/test_playbooks/fixtures/repository-20.yml
  tests/test_playbooks/fixtures/repository-3.yml
  tests/test_playbooks/fixtures/repository-4.yml
  tests/test_playbooks/fixtures/repository-5.yml
  tests/test_playbooks/fixtures/repository-6.yml
  tests/test_playbooks/fixtures/repository-7.yml
  tests/test_playbooks/fixtures/repository-8.yml
  tests/test_playbooks/fixtures/repository-9.yml
  tests/test_playbooks/product.yml
  tests/test_playbooks/repository.yml
  tests/test_playbooks/tasks/product.yml
  tests/test_playbooks/tasks/repository.yml
Labels: enhancement, ready to merge, triaged

#682 use subnets resource type for subnet6
  Makefile
  plugins/module_utils/foreman_helper.py
Labels: bug, triaged

#685 foreman_subnet: search domains by name
  plugins/modules/foreman_subnet.py
  tests/test_playbooks/fixtures/subnet-20.yml
Labels: bug, triaged
