Repository theforeman/foreman-ansible-modules, pull requests merged in 2020-12, with the labels that each got.

#1074 clean up inventory tests
  tests/test_playbooks/inventory_plugin.yml
  tests/test_playbooks/inventory_plugin_ansible.yml
  tests/test_playbooks/tasks/inventory_plugin.yml
Labels: inventory, triaged

#1088 correct documentation defaults in job_template
  plugins/modules/job_template.py
Labels: documentation, triaged

#1089 document how host.owner is looked up
  changelogs/fragments/1045-host-owner.yml
  plugins/modules/host.py
Labels: documentation, triaged

#1091 cv_version: ensure version param has a minor part
  changelogs/fragments/1087-content_view_version-safenet.yml
  plugins/modules/content_view_version.py
Labels: enhancement, triaged

#1069 Add Subscriptions to Activation Keys by Upstream Pool ID
  changelogs/fragments/541-activation-key-upstream-pool.yml
  plugins/modules/activation_key.py
Labels: enhancement, triaged, waiting on contributor

#1098 refactor resolved tracking into an own function
  plugins/module_utils/foreman_helper.py
Labels: refactor

#1065 add a role to manage sync plans
  changelogs/fragments/1065-sync-plans_role.yml
  roles/sync_plans/README.md
  roles/sync_plans/tasks/main.yml
  tests/fixtures/apidoc/sync_plans_role.json
  tests/test_playbooks/fixtures/sync_plans_role-0.yml
  tests/test_playbooks/sync_plans_role.yml
Labels: role, waiting on contributor

#1068 Activation key role
  changelogs/fragments/1068-activation-keys_role.yml
  roles/activation_keys/README.md
  roles/activation_keys/tasks/main.yml
  tests/fixtures/apidoc/activation_keys_role.json
  tests/test_playbooks/activation_keys_role.yml
  tests/test_playbooks/fixtures/activation_keys_role-0.yml
  tests/test_playbooks/fixtures/activation_keys_role-1.yml
Labels: role, triaged, waiting on contributor
