Repository theforeman/foreman-ansible-modules, pull requests merged in 2020-03, with the labels that each got.

#723 Refactor mixins wrt organizations
  plugins/module_utils/foreman_helper.py
  plugins/modules/foreman_hostgroup.py
  plugins/modules/foreman_scc_account.py
  plugins/modules/katello_activation_key.py
  plugins/modules/katello_content_credential.py
  plugins/modules/katello_content_view.py
  plugins/modules/katello_host_collection.py
  plugins/modules/katello_lifecycle_environment.py
  plugins/modules/katello_product.py
  plugins/modules/katello_sync_plan.py
Labels: needs reviewers, refactor

#591 Add inventory plugin from ansible/ansible to collection
  plugins/inventory/foreman.py
Labels: triaged

#724 Rename entity_spec and make it work in non-entity modules
  docs/developing.md
  plugins/module_utils/foreman_helper.py
  plugins/modules/foreman_architecture.py
  plugins/modules/foreman_auth_source_ldap.py
  plugins/modules/foreman_bookmark.py
  plugins/modules/foreman_compute_attribute.py
  plugins/modules/foreman_compute_profile.py
  plugins/modules/foreman_compute_resource.py
  plugins/modules/foreman_config_group.py
  plugins/modules/foreman_domain.py
  plugins/modules/foreman_environment.py
  plugins/modules/foreman_external_usergroup.py
  plugins/modules/foreman_global_parameter.py
  plugins/modules/foreman_host.py
  plugins/modules/foreman_host_power.py
  plugins/modules/foreman_hostgroup.py
  plugins/modules/foreman_installation_medium.py
  plugins/modules/foreman_job_template.py
  plugins/modules/foreman_location.py
  plugins/modules/foreman_model.py
  plugins/modules/foreman_operatingsystem.py
  plugins/modules/foreman_organization.py
  plugins/modules/foreman_os_default_template.py
  plugins/modules/foreman_provisioning_template.py
  plugins/modules/foreman_ptable.py
  plugins/modules/foreman_realm.py
  plugins/modules/foreman_role.py
  plugins/modules/foreman_scc_account.py
  plugins/modules/foreman_scc_product.py
  plugins/modules/foreman_search_facts.py
  plugins/modules/foreman_setting.py
  plugins/modules/foreman_smart_class_parameter.py
  plugins/modules/foreman_snapshot.py
  plugins/modules/foreman_subnet.py
  plugins/modules/foreman_user.py
  plugins/modules/foreman_usergroup.py
  plugins/modules/katello_activation_key.py
  plugins/modules/katello_content_credential.py
  plugins/modules/katello_content_view.py
  plugins/modules/katello_content_view_filter.py
  plugins/modules/katello_content_view_version.py
  plugins/modules/katello_host_collection.py
  plugins/modules/katello_lifecycle_environment.py
  plugins/modules/katello_manifest.py
  plugins/modules/katello_product.py
  plugins/modules/katello_repository.py
  plugins/modules/katello_sync.py
  plugins/modules/katello_sync_plan.py
  plugins/modules/katello_upload.py
  tests/test_foreman_spec_helper.py
Labels: needs reviewers, refactor, triaged

#732 improve repo_set error when it can't find a set
  plugins/modules/katello_repository_set.py
Labels: enhancement, needs reviewers

#729 Check for missing commits vs devel for inventory plugin
  plugins/inventory/foreman.py
Labels: enhancement, triaged, waiting on contributor

#759 add missing provisioning params to foreman_host
  plugins/modules/foreman_host.py
  plugins/modules/foreman_subnet.py
  tests/test_playbooks/tasks/host.yml
Labels: enhancement

#580 Fixes #579 - Added support to manage foreman SCAP content.
  plugins/module_utils/foreman_helper.py
  plugins/modules/foreman_scap_content.py
  tests/conftest.py
  tests/fixtures/apidoc/scap_content.json
  tests/test_playbooks/data/ssg-firefox-ds.xml
  tests/test_playbooks/fixtures/scap_content-0.yml
  tests/test_playbooks/fixtures/scap_content-1.yml
  tests/test_playbooks/fixtures/scap_content-2.yml
  tests/test_playbooks/fixtures/scap_content-3.yml
  tests/test_playbooks/fixtures/scap_content-4.yml
  tests/test_playbooks/fixtures/scap_content-5.yml
  tests/test_playbooks/scap_content.yml
  tests/test_playbooks/tasks/scap_content.yml
Labels: enhancement, needs reviewers, triaged

#769 Add http_proxy opts to repository
  plugins/modules/katello_repository.py
Labels: enhancement, triaged
