Repository theforeman/foreman-ansible-modules, pull requests merged in 2021-11, with the labels that each got.

#1286 Convert2RHEL role
  .github/workflows/main.yml
  changelogs/fragments/convert2rhel.yml
  roles/content_rhel/README.md
  roles/content_rhel/defaults/main.yml
  roles/content_rhel/tasks/main.yml
  roles/convert2rhel/README.md
  roles/convert2rhel/defaults/main.yml
  roles/convert2rhel/tasks/activation_keys.yml
  roles/convert2rhel/tasks/host_groups.yml
  roles/convert2rhel/tasks/main.yml
  roles/convert2rhel/tasks/products_and_repos.yml
  roles/manifest/tasks/main.yml
  tests/fixtures/apidoc/convert2rhel.json
  tests/test_playbooks/convert2rhel.yml
  tests/test_playbooks/fixtures/convert2rhel-1.yml
  tests/test_playbooks/fixtures/convert2rhel-2.yml
  tests/test_playbooks/fixtures/convert2rhel-3.yml
  tests/test_playbooks/fixtures/convert2rhel-4.yml
  tests/test_playbooks/fixtures/convert2rhel-5.yml
  tests/test_playbooks/fixtures/convert2rhel-6.yml
  tests/test_playbooks/fixtures/convert2rhel-7.yml
  tests/test_playbooks/fixtures/convert2rhel-8.yml
Labels: enhancement, triaged

#1308 Convert2RHEL - support for Oracle 7
  roles/convert2rhel/README.md
  roles/convert2rhel/defaults/main.yml
  roles/convert2rhel/tasks/activation_keys.yml
  roles/convert2rhel/tasks/host_groups.yml
  roles/convert2rhel/tasks/products_and_repos.yml
  tests/test_playbooks/convert2rhel.yml
  tests/test_playbooks/fixtures/convert2rhel-1.yml
  tests/test_playbooks/fixtures/convert2rhel-10.yml
  tests/test_playbooks/fixtures/convert2rhel-11.yml
  tests/test_playbooks/fixtures/convert2rhel-12.yml
  tests/test_playbooks/fixtures/convert2rhel-13.yml
  tests/test_playbooks/fixtures/convert2rhel-2.yml
  tests/test_playbooks/fixtures/convert2rhel-3.yml
  tests/test_playbooks/fixtures/convert2rhel-4.yml
  tests/test_playbooks/fixtures/convert2rhel-5.yml
  tests/test_playbooks/fixtures/convert2rhel-6.yml
  tests/test_playbooks/fixtures/convert2rhel-7.yml
  tests/test_playbooks/fixtures/convert2rhel-8.yml
  tests/test_playbooks/fixtures/convert2rhel-9.yml
Labels: triaged

#1210 Add role to publish a list of content views
  changelogs/fragments/1209-content_views_role.yml
  roles/content_view_publish/README.md
  roles/content_view_publish/tasks/main.yml
  tests/fixtures/apidoc/content_view_publish_role.json
  tests/test_playbooks/content_view_publish_role.yml
  tests/test_playbooks/fixtures/content_view_publish_role-0.yml
  tests/test_playbooks/fixtures/content_view_publish_role-1.yml
Labels: enhancement, triaged, role
