Repository theforeman/foreman-ansible-modules, pull requests merged in 2021-04, with the labels that each got.

#1116 Add role for managing hostgroups
  changelogs/fragments/1116-hostgroups-role.yml
  roles/hostgroups/README.md
  roles/hostgroups/tasks/main.yml
  tests/fixtures/apidoc/hostgroups_role.json
  tests/test_playbooks/fixtures/hostgroups_role-0.yml
  tests/test_playbooks/fixtures/hostgroups_role-1.yml
  tests/test_playbooks/fixtures/hostgroups_role-2.yml
  tests/test_playbooks/hostgroups_role.yml
Labels: enhancement, triaged, waiting on contributor

#1200 content_rhel role: add products to sync plan only when enabled
  roles/content_rhel/tasks/main.yml
Labels: triaged

#1195 Add content_credentials role
  changelogs/fragments/1196-content_credentials-role.yml
  roles/content_credentials/README.md
  roles/content_credentials/tasks/main.yml
  tests/fixtures/apidoc/content_credentials_role.json
  tests/test_playbooks/content_credentials_role.yml
  tests/test_playbooks/fixtures/content_credentials_role-0.yml
  tests/test_playbooks/fixtures/content_credentials_role-1.yml
Labels: enhancement, triaged
