Repository theforeman/foreman-ansible-modules, pull requests merged in 2021-06, with the labels that each got.

#1232 Fixes #32189 - add task action to callback
  plugins/callback/foreman.py
Labels: enhancement, triaged

#1238 Move CHANGELOG to bottom of docs index
  docs/index.rst
Labels: documentation, triaged

#1251 update katello apidoc to 4.1
  tests/fixtures/apidoc/katello.json
Labels: triaged
